fix(DTFS2-5888-5868): Amendments bug - effective date and first task email
UK-Export-Finance/dtfs2 pull request #1055
Opened 2022-06-30 14:53 UTC by Zainzzkk

# Issues: 
* effective date was not showing on amendments detail page (DTFS2-5868)
* email was not being sent for first task

# Changes made:
* added effective date based on if automatic or manual amendment so is displayed
* updated e2e tests
* added helper for sending first task email
* added api-test

2022-06-30 15:05 UTC, IgnatG commented on trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
> +  const urlOrigin = process.env.TFM_URI;
I'm not sure if this is coming from env variables for the other tasks?

2022-07-01 08:24 UTC, abhi-markan commented on trade-finance-manager-api/src/v1/controllers/amendment.controller.js
> +const { amendmentEmailEligible, sendAutomaticAmendmentEmail, sendManualDecisionAmendmentEmail, sendManualBankDecisionEmail, sendFirstTaskEmail } = require('../helpers/amendment.helpers');
I normally list functions if more than three in new lines, purely a personal preference not necessary.
Thought I'll add this as a suggestion.

2022-07-01 08:50 UTC, Zainzzkk commented on e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-underwriter-declined.spec.js
> +    amendmentsPage.amendmentDetails.row(1).effectiveDate().should('contain', '-');
done

2022-07-01 08:51 UTC, Zainzzkk commented on trade-finance-manager-api/src/v1/controllers/amendment.controller.js
> +          await sendFirstTaskEmail(firstTaskVariables);
the whole thing is in a try catch block and I have another one in sendFirstTaskEmail  just incase

2022-07-01 09:04 UTC, abhi-markan requested changes
Sorry missed out constant on few other places.

2022-07-01 09:04 UTC, abhi-markan commented on e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/8. amendment-details-manual-approval.spec.js
> +      amendmentsPage.amendmentDetails.row(1).effectiveDate().should('contain', '-');
Missing constant

2022-07-01 09:06 UTC, Zainzzkk commented on e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-withdraw.spec.js
> +    amendmentsPage.amendmentDetails.row(1).effectiveDate().should('contain', '-');
done

2022-07-01 09:06 UTC, Zainzzkk commented on e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/8. amendment-details-manual-approval.spec.js
> +      amendmentsPage.amendmentDetails.row(1).effectiveDate().should('contain', '-');
done

2022-07-01 09:09 UTC, abhi-markan approved these changes

2022-07-01 09:48 UTC, merged