Fix(DTFS2): fix vulnerable endpoints on external api
UK-Export-Finance/dtfs2 pull request #1756
Opened 2023-06-19 10:45 UTC by ChristianMcc

## Introduction
Just casting to a typescript interface doesn't remove extra properties as at compile time the types are stripped away, leaving javascript passing on the whole req.body still. Added in object destructuring to remove any extra fields.

##Resolution
Add object destructuring to two endpoints in external API

2023-06-20 13:01 UTC, ChristianMcc commented on external-api/api-tests/v1/eStore.api-test.ts
> +import { app } from '../../src/createApp';
Mocking and testing in this file LGTM for testing the injection :)

2023-06-21 10:57 UTC, abhi-markan requested changes
Good work, few comments to address please.

2023-06-21 10:57 UTC, abhi-markan commented on external-api/src/v1/controllers/premium-schedule.controller.ts
> +    if (objectIsEmpty(premiumSchedulePayload) || premiumSchedulePayload.facilityURN === 'PENDING') {
Can `PENDING` please be picked from Constant.

2023-06-21 10:57 UTC, abhi-markan commented on external-api/src/v1/controllers/premium-schedule.controller.ts
> +          `Error calling POST Premium schedule with facilityURN: ${premiumSchedulePayloadFormatted.facilityURN} \n`,
Can we please use `%s` specifier in the console.error.

```
console.error('Error calling POST Premium schedule with facilityURN %s:', premiumSchedulePayloadFormatted.facilityURN, error);
```

2023-06-23 11:03 UTC, ChristianMcc commented on external-api/api-tests/v1/eStore.api-test.ts
> +// eslint-disable-next-line @typescript-eslint/no-var-requires
This is used across every file in the external API, might be a bit of a bigger piece of work to remove this (couldn't figure out how to do it quickly)

2023-06-23 11:28 UTC, abhi-markan approved these changes

2023-06-23 12:13 UTC, merged