Draft: fix(SSRF): Add missing validation to routes in portal and gef
UK-Export-Finance/dtfs2 pull request #1878
Opened 2023-07-26 13:06 UTC by JennyHumphries

### Introduction
This review is to clear the last 15 SSRF warnings [here](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning?query=is%3Aopen+branch%3Amain+rule%3Ajssecurity%3AS5144+).

### Resolution
* Added validation for mongo ids in `portal` (Warnings [427](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/427), [431](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/431), [439](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/439))
* Added validation for mongo ids in `gef-ui` (Warnings [391](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/391), [392](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/392), [393](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/393), [418](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/418), [419](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/419), [420](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/420), [421](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/421))
* Added postcode validation in `gef-ui` (Warning [394](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/394))
* Added companies house number validation in `gef-ui` (Warning [422](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning/422))

2023-07-26 15:23 UTC, ChristianMcc commented on gef-ui/server/services/__tests__/api.test.js
> +const fakeMongoId = 'ABCDEF123456789000000000';
Could we add in some tests to check false is returned from all these newly validated endpoints with the following mongo IDs: '../../../etc/passwd/', 'localhost', '{}', '[]', ''.

Might be worth just making a list of these as inputs and doing a test.each loop for each of the endpoints, something like:

```
const invalidFacilityUrnTestCases = [["123"], ["127.0.0.1"], ["{}"], ["[]"]];

describe("when application ID is invalid", () => {
  test.each(invalidMongoId)(
    "returns a 400 if you provide an invalid application ID: %s",
    async (facilityUrn) => {

      const response = await api.getApplication(invalidMongoId);

      expect(response).toEqual(false);
    }
  );
});
```

2023-07-27 16:04 UTC, ChristianMcc reviewed
Nice work, minor comments which I can take care of tomorrow :)

2023-07-27 16:04 UTC, ChristianMcc commented on portal/server/constants/regex.js
> +exports.FILE_NAME_REGEX = new RegExp(`\\.(${FILE_UPLOAD.ALLOWED_FORMATS.join('|')})$`);
Can this be changed to need at least 1 character before the .<FILE_EXTENSION> please

2023-07-29 09:51 UTC, abhi-markan requested changes
Lint error to resolve please.

2023-07-29 09:51 UTC, abhi-markan commented on portal/server/api.js
> +          success: response.data.success,
Various linting errors to resolve.

2023-08-02 15:24 UTC, IgnatG approved these changes

2023-08-02 15:25 UTC, abhi-markan approved these changes

2023-08-02 15:25 UTC, merged