fix(SR-8): sanitise db input additional changes
UK-Export-Finance/dtfs2 pull request #1955
Opened 2023-08-11 16:32 UTC by oscar-richardson-softwire

Additional changes for https://github.com/UK-Export-Finance/dtfs2/pull/1946

2023-08-11 16:36 UTC, abhi-markan requested changes
Few comments to address please.

2023-08-11 16:36 UTC, abhi-markan commented on portal-api/src/v1/gef/controllers/application.controller.js
> +    res.status(400).send({ status: 400, message: 'Invalid Deal Id' });
Missing return

2023-08-11 16:36 UTC, abhi-markan commented on portal-api/src/v1/gef/controllers/application.controller.js
> +    res.status(400).send({ status: 400, message: 'Invalid Deal Id' });
Missing return

2023-08-11 16:36 UTC, abhi-markan commented on portal-api/src/v1/gef/controllers/facilities.controller.js
> +    res.status(400).send({ status: 400, message: 'Invalid Facility Id' });
Missing return

2023-08-11 16:36 UTC, abhi-markan commented on portal-api/src/v1/gef/controllers/facilities.controller.js
> +    res.status(400).send({ status: 400, message: 'Invalid Facility Id' });
Missing return

2023-08-11 16:36 UTC, abhi-markan commented on portal-api/src/v1/gef/controllers/mandatoryCriteriaVersioned.controller.js
> +    res.status(400).send({ status: 400, message: 'Invalid Mandatory Criteria Id' });
Missing return

2023-08-11 16:59 UTC, abhi-markan approved these changes

2023-08-14 10:19 UTC, AlexBramhill commented on portal-api/src/v1/controllers/mandatoryCriteria.controller.js
> +  const versionAsNumber = Number(version);
Do we want to check that this isn't `nan` here?

We probably want to add the conditional check on line 21 to `typeof version !== 'string' || isNaN(version)`

2023-08-14 12:34 UTC, AlexBramhill commented on dtfs-central-api/src/v1/controllers/tfm/deal/tfm-delete-deal.controller.js
>    }
```suggestion
  }
```

2023-08-14 12:35 UTC, AlexBramhill commented on dtfs-central-api/src/v1/controllers/tfm/deal/tfm-delete-deal.controller.js
> +
```suggestion

```

2023-08-14 14:24 UTC, abhi-markan requested changes
Good work, few comments to address please.

2023-08-14 14:24 UTC, abhi-markan commented on utils/data-migration/helpers/database.js
> +  if (typeof updatedFacility.facilitySnapshot.ukefFacilityId !== 'string') {
Can we please use optional chaining there `updatedFacility?.facilitySnapshot?.ukefFactilityId...`

2023-08-14 16:05 UTC, AlexBramhill commented on portal-api/src/v1/gef/controllers/facilities.controller.js
> +  return res.status(422).send([{ errCode: 'MANDATORY_FIELD', errMsg: 'No Application ID and/or facility type sent with request' }]);
just fixing these tests

2023-08-14 16:17 UTC, AlexBramhill commented on gef-ui/server/utils/helpers.js
> +    const mappedErrorMessage = errorsForReference ? errorsForReference[el.status] : el.errMsg;
This was needed as we are renaming this field in `portal-api`

2023-08-15 10:02 UTC, AlexBramhill commented on portal-api/src/v1/gef/controllers/facilities.controller.js
> +  return res.status(422).send([{ errCode: 'MANDATORY_FIELD', errMsg: 'No Application ID and/or facility type sent with request' }]);
Is there a reason to prefer `status` here? I feel it could be a bit confusing with the actual response status?

2023-08-15 12:21 UTC, lmarrai-sw commented on portal-api/src/v1/gef/controllers/facilities.controller.js
> +  return res.status(422).send([{ errCode: 'MANDATORY_FIELD', errMsg: 'No Application ID and/or facility type sent with request' }]);
@AlexBramhill has moved this to #1963

2023-08-15 13:14 UTC, abhi-markan approved these changes

2023-08-15 13:17 UTC, merged