fix: fixed the `siteName` not updating in tfm
UK-Export-Finance/dtfs2 pull request #1979
Opened 2023-08-30 09:17 UTC by IgnatG

### Description
the `siteName` was not updating when eStore API calls were executing 

### Resolution
Updated the MongoDB calls to update the database differently

2023-09-01 10:39 UTC, abhi-markan submitted a review, later dismissed

2023-09-01 11:26 UTC, lmarrai-sw requested changes
Just two small comments from me:

2023-09-01 11:26 UTC, lmarrai-sw commented on external-api/src/v1/controllers/estore/eStore.controller.ts
> +            { $set: siteCreationResponse, 'siteCronJob.status': ESTORE_CRON_STATUS.FAILED, 'siteCronJob.failureDate': new Date() },
Should this be
```suggestion
            { $set: { siteCreationResponse, 'siteCronJob.status': ESTORE_CRON_STATUS.FAILED, 'siteCronJob.failureDate': new Date() } },
```
?

2023-09-01 11:26 UTC, lmarrai-sw commented on external-api/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
> +      // update the `tfm-deals` collection once the buyer and deal folders have been created
Should the comment say
```suggestion
      // update the `tfm-deals` collection once the buyer folder has been created
```
instead?

2023-09-03 14:23 UTC, IgnatG commented on external-api/src/v1/controllers/estore/eStore.controller.ts
> +            { $set: siteCreationResponse, 'siteCronJob.status': ESTORE_CRON_STATUS.FAILED, 'siteCronJob.failureDate': new Date() },
good spot! updated now

2023-09-03 14:24 UTC, IgnatG commented on external-api/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
> +      // update the `tfm-deals` collection once the buyer and deal folders have been created
good spot. I've updated that now

2023-09-05 07:38 UTC, abhi-markan approved these changes

2023-09-05 07:38 UTC, merged