Feat(DTFS2-6182): replace update party graphql endpoint with REST endpoint
UK-Export-Finance/dtfs2 pull request #2043
Opened 2023-09-06 14:32 UTC by francescastocco

## Introduction
We need to standardise the TFM API by moving away from having both gql and REST endpoints. We will move the gql endpoints to REST.

## Resolution
Replace the update party graphql endpoint with a REST endpoint as part of the gql -> rest migration in TFM API.

2023-09-18 10:10 UTC, ChristianMcc requested changes
Minor async change comment then can merge :)

2023-09-18 10:10 UTC, ChristianMcc commented on trade-finance-manager-api/src/v1/controllers/party.controller.js
> +      if (await canDealBeSubmittedToACBS(updatedDeal.dealSnapshot.submissionType)) {
I'm guessing was just copy pasted but I think this isn't an async function and doesn't need to be awaited

2023-09-18 10:10 UTC, ChristianMcc commented on trade-finance-manager-api/src/v1/controllers/tfm.controller.js
> +// This is never used - should I delete it?
Ah yes the function from deal.controller.js is the only one used right? Happy for this to be deleted

2023-10-02 13:14 UTC, AlexBramhill reviewed
Review non-mappings files

2023-10-04 15:05 UTC, merged