Chore/dtfs2 none/tidy root package json
UK-Export-Finance/dtfs2 pull request #2088
Opened 2023-09-29 17:28 UTC by AlexBramhill

# Issue
There are non-dev dependancies on the root of the repo

# Resolution
I've moved these to devDependancies

# Todo
Update `package.lock` once I can successfully `npm run ci:all`

2023-10-01 08:00 UTC, abhi-markan commented
Please adjust the commit title so it adheres to the standards.

2023-10-02 11:56 UTC, lmarrai-sw commented
@AlexBramhill I think we need to edit the lint config to tell it that any dependencies in the `e2e-tests` folder are only dev dependencies

2023-10-18 09:01 UTC, AlexBramhill commented on package.json
> +    "moment": "^2.29.4",
I don't know where this has suddenly appeared from and will delete

2023-10-18 18:04 UTC, lmarrai-sw commented on package.json
> +  "dependencies": {},
```suggestion
```

2023-10-18 18:04 UTC, lmarrai-sw commented on e2e-tests/.eslintrc.js
> +    'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
```suggestion
    'import/no-extraneous-dependencies': ['error'],
```
Is `devDependencies: true` not the default?

2023-10-20 07:54 UTC, lmarrai-sw submitted a review, later dismissed

2023-10-20 10:09 UTC, abhi-markan approved these changes

2023-10-20 10:09 UTC, abhi-markan commented
@AlexBramhill merge conflicts to resolve please.

2023-10-23 17:20 UTC, abhi-markan requested changes
Linting errors to address.

2023-11-08 09:16 UTC, abhi-markan submitted a review, later dismissed

2023-11-08 09:28 UTC, abhi-markan approved these changes

2023-11-08 10:33 UTC, merged