fix: seed random company names to prevent 3% chance of collision that causes test failure
UK-Export-Finance/dtfs2 pull request #2144
Opened 2023-10-02 16:27 UTC by lmarrai-sw

## Introduction

@AlexBramhill and I noticed that the `dashboard-deals-filter-on-wrong-pagination-page.spec.js` test in the `portal` e2e tests would randomly fail on PRs that hadn't affected it at all, so we investigated it.

It creates 30 deals with random company names (using `chance.company()` from the `chance` package. It then filters the dashboard by searching by the first company name that was generated, assuming that this should return exactly 1 deal (the first deal).

However, `chance.company()` picks a random company name from a list of roughly 900. That gives ~3% chance that at least one of the other 29 deals have exactly the same company name as the first deal, meaning the test will fail because the dashboard filter will return (at least) 2 deals instead of 1.

## Resolution

I've introduced a new class, `RandomValueGenerator`, for the e2e tests that uses a seeded version of `chance`. This way each test run should be repeatable by using the exact same random company names (assuming the test code and the `chance` code doesn't change). This should eliminate the 3% chance that the test fails, which was a source of flakey e2e test results.

Note there is a chance that in the future we edit the test in such a way that the seeded random value generator will end up generating the same company name for another deal as it does for the first. If this happens, it will happen 100% of the time, so it should be easy to debug. We can then pick a different seed for `chance` to fix the issue.

2023-10-02 16:28 UTC, lmarrai-sw commented on e2e-tests/.eslintrc.js
> +    ecmaVersion: 14,
We need ecma script 13 support for the private class properties I have used in `RandomValueGenerator` (the hashes)

2023-10-02 16:43 UTC, AlexBramhill approved these changes

2023-10-02 16:51 UTC, abhi-markan requested changes
Great work, few comments to address please.

2023-10-02 16:51 UTC, abhi-markan commented on e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-sort.spec.js
> +          companyName = randomValueGenerator.companyName().toLowerCase();
Can `toLowerCase()` be added as an argument please.

2023-10-02 16:51 UTC, abhi-markan commented on e2e-tests/support/random-value-generator.js
> +export class RandomValueGenerator {
Can we please add some documentation from PR description for context.

2023-10-02 16:58 UTC, abhi-markan commented
One minor comment regarding commit name, please can it match the standard. Thanks

2023-10-06 09:38 UTC, abhi-markan approved these changes
LGTM 👍🏼  Good work

2023-10-06 10:13 UTC, merged