feat(FN-974): Notify email for incoming report
UK-Export-Finance/dtfs2 pull request #2161
Opened 2023-10-13 07:53 UTC by francescastocco

## Introduction
We need to notify PDC Inputters when the banks have submitted a utilisation report.

## Resolution
- Created endpoint in portal-api, which is called when user clicks `Confirm and Send` button on the utilisation report upload pages
- Used `sendEmail` function to use Notify to send email
- Added new email template to constants file
- Added API tests for role & auth validation

## To Do
Create an environment variable called `PDC_INPUTTERS_EMAIL_RECIPIENT`

2023-10-13 09:07 UTC, ChristianMcc requested changes
LGTM! Small env variable related changes that might help you :D

2023-10-13 09:07 UTC, ChristianMcc commented on portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
> +    res.status(200).send(month);
Maybe just return true or something here leaving in the comment to make the code scanning happy for now (know it's only temporary code!)

2023-10-13 13:48 UTC, francescastocco commented on docker-compose.dev.yml
> +      - PDC_INPUTTERS_EMAIL_RECIPIENT=francesca.stocco@ukexportfinance.gov.uk
Oooh yes, that would be bad

2023-10-13 14:47 UTC, francescastocco commented on portal-api/src/constants/email-template-ids.js
> +const PASSWORD_RESET = '6935e539-1a0c-4eca-a6f3-f239402c0987';
Ooh yes, I refactored the [password reset file](https://github.com/UK-Export-Finance/dtfs2/pull/2161/files#diff-873955b5374628a0d2e97c56a34970251cb10cdd40a24fbbc8f0bc7a169adeb6) as I thought it was better to use a constant, is this ok or should I have left it? I did actually inadvertently test it worked when doing a password reset but doubt we'd regression test this?

2023-10-17 09:00 UTC, ChristianMcc approved these changes
Nice :)

2023-10-17 13:12 UTC, ChristianMcc approved these changes

2023-10-17 13:24 UTC, merged