feat(FN-980): update error handling
UK-Export-Finance/dtfs2 pull request #2164
Opened 2023-10-16 08:26 UTC by francescastocco

## Introduction
Improve error handling of previous reports page

## Resolution
- Not return 200 if something has gone wrong

2023-10-16 09:40 UTC, AlexBramhill commented on dtfs-central-api/src/v1/controllers/portal/utilisation-report-service/previous-reports.controller.js
>      console.error('Unable to get utilisation reports %s', error);
Any reason we're not returning a 500 here?

2023-10-16 09:40 UTC, AlexBramhill commented on portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
>      console.error('Unable to get previous reports %s', error);
Any reason for not returning a 500 here?

2023-10-19 17:18 UTC, ChristianMcc requested changes
When we return an error to the frontend are we display as if there are no reports or displaying an error page? I'd semi expect that if an API call fails and something goes wrong that we would display the 'something went wrong' page rather than say 0 reports

2023-10-19 17:18 UTC, ChristianMcc commented on dtfs-central-api/src/v1/controllers/portal/utilisation-report-service/previous-reports.controller.js
> +    res.status(500).send({ status: 500, message: error });
As mentioned in person - can we change returning the code error to a generic 'Failed to get utilisation reports' style string

2023-10-19 17:18 UTC, ChristianMcc commented on portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
> +    res.status(500).send({ status: 500, message: error });
ditto

2023-10-20 11:07 UTC, francescastocco commented
> When we return an error to the frontend are we display as if there are no reports or displaying an error page? I'd semi expect that if an API call fails and something goes wrong that we would display the 'something went wrong' page rather than say 0 reports

I've moved the api call into the try/catch so will catch any errors and render the `problem-with-service` page

2023-10-23 17:15 UTC, abhi-markan requested changes
Couple of comments to address please.

2023-10-23 17:15 UTC, abhi-markan commented on dtfs-central-api/src/v1/controllers/portal/utilisation-report-service/previous-reports.controller.js
> +    console.error('Unable to get utilisation reports %O', error);
Looks like we are using `%s` everywhere else.

2023-10-23 17:15 UTC, abhi-markan commented on portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
> +    console.error('Unable to get previous reports %O', error);
Same as above.

2023-10-26 08:32 UTC, abhi-markan approved these changes

2023-10-26 08:38 UTC, ChristianMcc approved these changes

2023-10-26 08:45 UTC, merged