feat(FN-1294): add payment report officer nav items to shared nav bar
UK-Export-Finance/dtfs2 pull request #2192
Opened 2023-10-24 16:36 UTC by toddym42

## Introduction
- use the standard DTFS header for utilisation report pages
- add the utilisation report nav items to the main nav bar for users with the `'payment-report-officer'` role.
  - Report GEF utilisation and fees
  - Previous GEF reports

## Resolution
- removed the custom `utilisation-report-service/index.njk` page wrapper and replaced use with the generic `index.njk`. This means all pages now use the same header
- refactored `'payment-officer'` role to `'payment-report-officer'`, and added permission to all projects
- refactored logic in `portal/templates/_partials/primary-navigation.njk` that determines which nav items are displayed. Now checks each nav item to see if you have permission to view it, where previously we rendered a different set based on the role (or roles) the user had. This prevents the need to have to think about combinations of roles, and the order in which we'd need to check the combinations to see what should be rendered

2023-10-25 08:15 UTC, ChristianMcc requested changes
Nice work! Small behaviour question and then need to fix the 'mock-data-loader' (the seeding of data) with your change to the array -> object which I like

2023-10-25 08:15 UTC, ChristianMcc commented on portal/component-tests/partials/primary-navigation.component-test.js
> +    itDoesNotRenderAHomeLink();
In previous behaviour a user would have a home link only, while I'm not sure if this is right or wrong I'd prefer to not change existing behaviour so can we keep that logic please?

2023-10-25 08:15 UTC, ChristianMcc commented on utils/mock-data-loader/portal/users.js
> +const USERS = {
big fan of this change, nice one :) 
In insert-mocks.js we iterate over this USERS array and as it's now an object we'll have to iterate over Object.entries or something here to turn this object into an array to insert all the users into the DB.
Hard to test without having a local setup but if you check to fix there first can check your branch out and test it if you don't have a working setup by then!

2023-10-25 11:22 UTC, JoshBinns2000 commented on portal/component-tests/partials/primary-navigation.component-test.js
> +const ROLES = require('../../server/constants/roles');
Minor change but maybe this could be replaced with `const { ROLES } = require('../../server/constants')`

2023-10-25 16:04 UTC, ChristianMcc commented
There's a few failing portal tests to do with access that are probably from the rename. Personally I'd wait to debug them with a real setup before looking into them so you can test this.
As far as I'm concerned this is good to go with a couple of tests to fix so when you have a setup and can test this ticket will approve and can merge then!
@JoshBinns2000 you can rebase on top of this as it is now to get these changes if you haven't as I don't foresee many other changes happening :)

2023-10-25 16:08 UTC, toddym42 commented
> There's a few failing portal tests to do with access that are probably from the rename. Personally I'd wait to debug them with a real setup before looking into them so you can test this. As far as I'm concerned this is good to go with a couple of tests to fix so when you have a setup and can test this ticket will approve and can merge then! @JoshBinns2000 you can rebase on top of this as it is now to get these changes if you haven't as I don't foresee many other changes happening :)

@ChristianMcc - I'd looked into the test failures and apparently they're all existing ones, and I believe they're already in the process of being fixed separately. I have my access now, so will double-check for sure, and check that this is all working as we'd expect.

2023-10-27 09:11 UTC, ChristianMcc approved these changes

2023-10-27 16:20 UTC, ChristianMcc approved these changes

2023-10-27 16:21 UTC, merged