feat(FN-1615): add generic for express render options
UK-Export-Finance/dtfs2 pull request #3092
Opened 2024-05-03 10:10 UTC by JoshBinns2000

## Introduction :pencil2:
It would be nice to have a way of defining the type we want to use for the express `res.render` method.

## Resolution :heavy_check_mark:
Adds a new declaration file to merge the declaration for the express `core.Response.render` function.

## Miscellaneous :heavy_plus_sign:

2024-05-23 13:58 UTC, abhi-markan requested changes
If this approach is must then I would prefer being applied across other UI microservices for consistency.

2024-05-23 13:58 UTC, abhi-markan commented on trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
> +      userToken,
Various GitHub alerts on type any.

2024-05-23 13:58 UTC, abhi-markan commented on trade-finance-manager-ui/server/types/express-serve-static-core.d.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Please remove inline rule override.

2024-06-04 07:26 UTC, abhi-markan commented
@JoshBinns2000 is this PR still required or can we close this?

2024-06-05 09:03 UTC, closed without merging

2024-06-05 09:04 UTC, JoshBinns2000 commented
The pattern of adding a `render<View>` function at the controller level has been added in preference to this typescript-first approach