chore(dtfs2-none): fix typo
UK-Export-Finance/dtfs2 pull request #3146
Opened 2024-05-23 08:08 UTC by natdeanlewissoftwire

## Introduction :pencil2:
Generic copy updates and refactoring that I found as part of my poking around the service post rampup

## Resolution :heavy_check_mark:
Makes the example 8 digit companies house actually be 8 digits, and use constants where possible in tests

## Miscellaneous :heavy_plus_sign:
Adding spaces, punctuation, etc
Make constant naming consistent throughout codebase (e.g. INVALID_WITH_SPACE used everywhere, rather than also having INVALID_SPACE in some places)

2024-05-23 08:49 UTC, AlexBramhill approved these changes
could you update assignee (to yourself) and label (to type chore), then lgtm (I did your other pr so you can see what it looks like)

2024-05-23 13:39 UTC, abhi-markan requested changes

2024-05-23 13:39 UTC, abhi-markan commented on e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-supply-contract-validation.spec.js
> +    contractAboutSupplier.indemnifierCompaniesHouseRegistrationNumber().clear().type('89898989 ');
Constant please

2024-05-23 13:39 UTC, abhi-markan commented on e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-supply-contract-validation.spec.js
> +    contractAboutSupplier.indemnifierCompaniesHouseRegistrationNumber().clear().type('89898989 ');
Can all the instances be from constant defined in 'e2e-tests'

2024-05-24 09:06 UTC, natdeanlewissoftwire commented on e2e-tests/gef/cypress/e2e/exporter/exporter-correspondence-address.spec.js
> +      companiesHouse.regNumberField().type('89898989');
Yep, good idea :)

2024-06-03 08:27 UTC, abhi-markan submitted a review, later dismissed

2024-06-04 14:08 UTC, abhi-markan commented
@natdeanlewissoftwire failing E2E test.

2024-06-05 12:49 UTC, natdeanlewissoftwire commented
> @natdeanlewissoftwire failing E2E test.

@abhi-markan fixed thanks - should be ready for re-approval

2024-06-06 09:56 UTC, abhi-markan approved these changes

2024-06-06 09:56 UTC, merged