feat(FN-2406): use common report data validation for upload
UK-Export-Finance/dtfs2 pull request #3447
Opened 2024-09-02 08:02 UTC by RLavender98

## Introduction :pencil2:
In a previous PR we moved the validation of report data to dtfs-central-api for the 'check the report page'.
We should use the same validation for the upload journey since:
- The new validation is slightly stricter than the previous validation in dtfs-central-api so this will ensure consistency across the validation
- We will only have to update one set of validation rules moving forwards as rules change

## Resolution :heavy_check_mark:
- Replace the report data validation in the upload utilisation report payload validator with the newly moved stricter report data validation logic from portal-api.

## Miscellaneous :heavy_plus_sign:
- Moved the payload validation to the `routes/middleware` folder where the other payload validators are defined

2024-09-03 09:58 UTC, sw-mattw submitted a review, later dismissed
Nice, looks good, needs UKEF a review though

2024-09-03 12:08 UTC, ttbarnes requested changes
Great work 🎉 Just a couple of comments

2024-09-03 12:08 UTC, ttbarnes commented on dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-upload-utilisation-report-payload.test.ts
> +    });
Can we add a test to check the validation errors are returned in the response? e.g

```ts
expect(res.send).toHaveBeenCalledWith(expected);
```

2024-09-03 12:08 UTC, ttbarnes commented on dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-upload-utilisation-report-payload.ts
> +  ].filter(Boolean);
Can we extract `reportDataMapped` and the `validationErrors` mapping and filtering logic into their own standalone functions? As there's a fair amount going on here. Would also then be able to write unit tests for these and make the middleware and it's unit test simpler

2024-09-04 12:47 UTC, ttbarnes approved these changes

2024-09-05 08:52 UTC, Zainzzkk approved these changes

2024-09-05 09:33 UTC, merged