fix(DTFS2-7347): validate facility section is complete on resubmission
UK-Export-Finance/dtfs2 pull request #3459
Opened 2024-09-04 13:12 UTC by MarRobSoftwire

## Introduction :pencil2:
The submit button was displayed when resubmitting a deal when the FED had not been provided

## Resolution :heavy_check_mark:
Check the facilities section is complete when rendering the submit button

2024-09-04 13:20 UTC, MarRobSoftwire commented on gef-ui/server/models/application.js
Need to add test coverage (including e2e)

2024-09-10 11:00 UTC, ttbarnes requested changes
One minor comment otherwise LGTM - nice constants improvements

2024-09-10 11:00 UTC, ttbarnes commented on e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facilities-change-all-AIN.spec.js
> +
I think we should split these up so the assertions are more specific/clearer, would help for future debugging as well. What do you think?

```js
it('allows a facility with a bank review date to be submitted', () => { }

it('does not allow a facility without a bank review date to be submitted', () => { }

it('allows a facility with a facility end date to be submitted', () => { }

it('does not allow a facility without a facility end date to be submitted', () => { }
```

2024-09-10 15:59 UTC, ttbarnes approved these changes

2024-09-11 09:31 UTC, merged