fix(DTFS2-6655): create cy.createGefApplicationReadyForCheck() to create individual GEF application through UI
UK-Export-Finance/dtfs2 pull request #3460
Opened 2024-09-04 14:52 UTC by vamshidharukef

## Introduction :pencil2:
For some of the e2e tests after validation is put on users, some tests fail as users with role maker cannot access end point http://localhost:5001/v1/users

## Resolution :heavy_check_mark:
Create cy.createBssApplicationReadyForReview() for creating BSS/EWCS deals through UI
Update commnds.js to use cy.createBssApplicationReadyForReview

2024-09-10 08:42 UTC, Zainzzkk reviewed
Can this be added to the tests where it is required please?

2024-09-10 15:16 UTC, ttbarnes requested changes

2024-09-22 18:58 UTC, Mihail1Ynakiev commented on e2e-tests/portal/cypress/support/portal/createGefDealReadyForCheck.js
> +const createGefDealReadyForCheck = () => {
> Same comment as in the BSS/EWCS PR please https://github.com/UK-Export-Finance/dtfs2/pull/3454#discussion_r1752054985

2024-09-30 13:23 UTC, ttbarnes commented
TODO - create a new branch and PR with DTFS2-7434 ticket.

2024-10-02 10:23 UTC, ttbarnes commented
Closing in favour of https://github.com/UK-Export-Finance/dtfs2/pull/3632

2024-10-02 10:23 UTC, closed without merging