feat(DTFS2-7353): add get cancellation endpoint to tfm api
UK-Export-Finance/dtfs2 pull request #3542
Opened 2024-09-18 14:09 UTC by MarRobSoftwire

## Introduction :pencil2:
tfm-api should get the cancellation object from dtfs-central-api. The dtfs-central-api is added in #3540 

## Resolution :heavy_check_mark:
Add cancellation endpoint, getting data from dtfs-central-api
Add api and unit tests

## Note ⚠️ 
This is branched off #3469

2024-09-19 16:16 UTC, MarRobSoftwire commented on trade-finance-manager-api/src/v1/deals/routes.js
> +  .all(validateDealCancellationEnabled, validation.dealIdValidation, handleExpressValidatorResult)
Note to self: add RBAC to the new endpoint once 7370 is merged in

2024-09-23 09:50 UTC, ttbarnes requested changes
Nice work, few minor comments

2024-09-23 09:50 UTC, ttbarnes commented on libs/common/src/middleware/feature-flags/deal-cancellation.ts
> +    console.error(`Deal Cancellation feature flag disabled, accessing ${req.originalUrl}`);
Should this be `.info` since technically it's not an error

2024-09-23 09:50 UTC, ttbarnes commented on trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.get.api-test.ts
> +    const getTfmDealCancellationUrl = ({ id }: { id: string }) => `/v1/deals/${id}/cancellation`;
Could we create a DRY test helper for this, noticed it's repeated and with different names:

```ts
const getTfmDealCancellationUrl = ({ id }: { id: string }) => `/v1/deals/${id}/cancellation`;
const getTfmDealCancellationUpdateUrl = ({ id }: { id: string }) => `/v1/deals/${id}/cancellation`;
```

2024-09-23 09:50 UTC, ttbarnes commented on trade-finance-manager-api/src/v1/api.js
> + * Updates the deal cancellation object on a TFM AIN or MIN deal
Do we need to mention AIN and MIN here, this function doesn't specifically care about this?

2024-09-23 11:18 UTC, ttbarnes approved these changes

2024-09-24 13:03 UTC, merged