feat(FN-3449): utilisation report premium payments tab copy update
UK-Export-Finance/dtfs2 pull request #3601
Opened 2024-10-01 11:37 UTC by Zainzzkk

## Introduction :pencil2:
This PR updates the content on the utilisation report premium payments section

## Resolution :heavy_check_mark:
* Copy change
* Added data-cy
* Updated test

2024-10-01 14:46 UTC, ttbarnes approved these changes
Great work

2024-10-01 15:34 UTC, RLavender98 requested changes

2024-10-01 15:34 UTC, RLavender98 commented on trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
> +        <p class="govuk-body" data-cy="received-payments-text">Received payments are entered against reported fees. When payments show as matched, the adjustment data for keying into ACBS will be aut
Should this change not be for only the read only users with PDC_RECONCILE still seeing the same text?

2024-10-02 09:58 UTC, Zainzzkk commented on trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
> +          <p class="govuk-body" data-cy="when-payments-show-text">
done

2024-10-02 09:58 UTC, Zainzzkk commented on trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
> +        /Received payments are entered against reported fees. When payments show as matched, the adjustment data for keying into ACBS will be automatically generated./,
added

2024-10-02 12:28 UTC, RLavender98 approved these changes

2024-10-02 14:56 UTC, merged