fix(dtfs2-7577): fix console logging in gef api error handler
UK-Export-Finance/dtfs2 pull request #3792
Opened 2024-10-31 11:47 UTC by AlexBramhill

## Introduction :pencil2:
adds better logs around our api error handling

2024-11-01 10:55 UTC, ttbarnes submitted a review, later dismissed
Great work

2024-11-04 10:32 UTC, abhi-markan requested changes
Thanks for this @AlexBramhill this PR can be now closed.

2024-11-04 10:39 UTC, AlexBramhill commented
> Thanks for this @AlexBramhill this PR can be now closed.

Are you sure we don't still need this? We should probably log all non OK errors?

2024-11-04 11:06 UTC, abhi-markan requested changes

2024-11-04 11:06 UTC, abhi-markan commented on gef-ui/server/utils/helpers.js
> +  console.error({ code, response });
```suggestion
  console.error('API error %s %o', code, response);
```

2024-11-04 11:16 UTC, ttbarnes approved these changes

2024-11-04 15:32 UTC, abhi-markan approved these changes

2024-11-04 15:32 UTC, merged