chore(DTFS2-7605): update dependabot to run during non working hours
UK-Export-Finance/dtfs2 pull request #3845
Opened 2024-11-01 15:40 UTC by AlexBramhill

## Introduction :pencil2:
Dependabot runs at a random time. When this is during working hours, it uses a lot of runners

## Resolution :heavy_check_mark:
* Change time to be midnight

## Miscellaneous ➕ 
* Added `.github/**` path to `test.yml` and `lint.yml`.

2024-11-01 15:43 UTC, ttbarnes requested changes
Can we create a ticket for this please, we can't have PRs with "none" in the title for release notes etc

2024-11-01 15:45 UTC, abhi-markan requested changes

2024-11-01 15:45 UTC, abhi-markan commented on .github/dependabot.yml
> -  #  Set the directory to `/` for
Can we leave this please

2024-11-01 15:53 UTC, abhi-markan submitted a review, later dismissed

2024-11-01 15:55 UTC, ttbarnes submitted a review, later dismissed

2024-11-01 17:06 UTC, Zainzzkk submitted a review, later dismissed

2024-11-01 17:09 UTC, Zainzzkk submitted a review, later dismissed

2024-11-01 17:12 UTC, ttbarnes commented on .github/dependabot.yml
> +# Automatic weekly dependencies updates
```suggestion
# Automatic dependencies updates
```

2024-11-04 10:13 UTC, ttbarnes approved these changes

2024-11-04 10:33 UTC, abhi-markan approved these changes

2024-11-04 13:36 UTC, abhi-markan approved these changes

2024-11-04 19:37 UTC, abhi-markan approved these changes

2024-11-04 22:11 UTC, ttbarnes approved these changes

2024-11-05 08:44 UTC, merged