feat(DTFS2-7612): refactor get facility controller to have consistent return type
UK-Export-Finance/dtfs2 pull request #3913
Opened 2024-11-08 16:21 UTC by MarRobSoftwire

## Introduction :pencil2:
Include a summary of the changes and related feature(s) or issue(s).

## Resolution :heavy_check_mark:
List all changes made to the codebase.

## Miscellaneous :heavy_plus_sign:
List any additional fixes or improvements.

2024-11-08 16:24 UTC, MarRobSoftwire commented on dtfs-central-api/src/v1/controllers/portal/facility/update-facility-status.controller.js
> +  if (!existingFacility) {
Remove this line - existing facility will no longer be null

2024-11-08 16:25 UTC, MarRobSoftwire commented on dtfs-central-api/src/v1/controllers/portal/facility/update-facility-status.controller.js
> +  const findAndUpdateResponse = await collection.findOneAndUpdate({ _id: { $eq: ObjectId(facilityId) } }, $.flatten(withoutId(update)), {
Maybe refactor `$.flatten(withoutId(update))` ?

2024-11-08 16:26 UTC, MarRobSoftwire commented on dtfs-central-api/src/v1/controllers/portal/facility/update-facility.controller.js
> +    if (!facility) {
remove this

2024-11-08 16:27 UTC, MarRobSoftwire commented on dtfs-central-api/src/v1/controllers/portal/facility/delete-facility.controller.ts
> +    if (!facility) {
remove this

2024-11-11 14:44 UTC, ttbarnes requested changes
Nice 😎 Few minor comments

2024-11-11 14:44 UTC, ttbarnes commented on dtfs-central-api/src/v1/controllers/portal/facility/update-facility-status.controller.js
> +const updateFacilityStatus = async ({ facilityId, status, auditDetails }) => {
Can we add some documentation whilst we're here?

2024-11-11 14:44 UTC, ttbarnes commented on dtfs-central-api/src/v1/controllers/portal/facility/update-facility.controller.js
> +    if (!ObjectId.isValid(facilityId)) {
I think we can remove this because this happens in `findOneFacility`

2024-11-11 15:05 UTC, ttbarnes approved these changes
LGTM

2024-11-11 16:00 UTC, merged