feat(FN-3576): create record correction request page backlink
UK-Export-Finance/dtfs2 pull request #3927
Opened 2024-11-13 15:22 UTC by RLavender98

## Introduction :pencil2:
When I am on the create record correction request page and I click the back button I want the fee record I had selected to remain selected.

## Resolution :heavy_check_mark:
- Use premium payments link helper to set back link on create record correction request page

Notes: This is based on the create record correction request button PR so we can add an e2e-test using the set up on that branch. This should not be merged until the base is merged.

2024-11-13 16:22 UTC, ttbarnes requested changes
2x really minor comments otherwise LGTM

2024-11-13 16:22 UTC, ttbarnes commented on e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction.spec.js
> +        backLink().click();
We can use `cy.clickBackLink()` instead 👍

2024-11-13 16:22 UTC, ttbarnes commented on e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction.spec.js
> +        premiumPaymentsTab.premiumPaymentsTable
Can we add an empty line after the URL assertion please, finding a little hard to read

2024-11-18 16:25 UTC, ttbarnes submitted a review, later dismissed

2024-11-18 17:17 UTC, sw-mattw submitted a review, later dismissed
Nice addition, looks good thanks

2024-11-25 10:52 UTC, ttbarnes approved these changes

2024-11-25 11:34 UTC, ttbarnes approved these changes

2024-11-25 11:38 UTC, sw-mattw approved these changes

2024-11-25 14:12 UTC, merged