feat(DTFS2-6892): move entra id to tfm api
UK-Export-Finance/dtfs2 pull request #3960
Opened 2024-11-27 16:59 UTC by AlexBramhill

## Introduction :pencil2:
As part of future SSO work, we will want the msal instance, and subsequently all entra processing, in tfm api as apposed to tfm ui

## Resolution :heavy_check_mark:
This PR moves existing code into appropriate places (tfm api, libs common), as well as adding in a login service in tfm ui to call tfm api.

2024-12-09 15:51 UTC, ttbarnes requested changes

2024-12-09 15:51 UTC, ttbarnes commented on libs/common/src/test-helpers/mock-builders/index.ts
> +export * from './mock-builder.mock.builder';
Could `mock-builder.mock-builder` just be in the index?

2024-12-09 15:51 UTC, ttbarnes commented on trade-finance-manager-api/src/v1/controllers/sso.controller.ts
> +}
Can we add a unit test please

2024-12-09 15:51 UTC, ttbarnes commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-login.test.ts
> +    function mockFailedGetAuthCodeUrl() {
Can we remove this? it's only used once, I think it'd be clearer to just have this in the one test

2024-12-09 15:51 UTC, ttbarnes commented on trade-finance-manager-ui/server/services/login.service.get-auth-code-url.test.ts
> +      expect(getAuthCodeUrlSpy).toHaveBeenCalledWith({ successRedirect });
Can we add a `toHaveBeenCalledTimes(1)` assertion just before this please

2024-12-09 15:51 UTC, ttbarnes commented on trade-finance-manager-ui/server/services/login.service.get-auth-code-url.test.ts
> +      it('returns the auth code url', async () => {
Can we use "it('should ..."` style descriptions please

2024-12-11 10:40 UTC, ttbarnes commented on trade-finance-manager-api/src/v1/controllers/sso.controller.ts
> +}
Resolving for a newer comment

2024-12-11 10:40 UTC, ttbarnes commented on trade-finance-manager-api/src/v1/controllers/sso.controller.ts
> +}
@AlexBramhill Do we have a unit test for this? Can't seem to find.

2024-12-11 10:40 UTC, ttbarnes commented on trade-finance-manager-ui/server/services/login.service.get-auth-code-url.test.ts
> +      expect(getAuthCodeUrlSpy).toHaveBeenCalledWith({ successRedirect });
Bump @AlexBramhill

2024-12-11 10:40 UTC, ttbarnes commented on trade-finance-manager-ui/server/services/login.service.get-auth-code-url.test.ts
> +      it('returns the auth code url', async () => {
@AlexBramhill bump, same with the test above instead if "it calls"

2025-01-10 11:18 UTC, rkontogianni commented on libs/common/src/errors/user-partial-login-data-not-defined.error.test.ts
> +    // Act
same as above

2025-01-10 11:19 UTC, rkontogianni commented on libs/common/src/errors/user-partial-login-data-not-defined.error.test.ts
> +    // Act
same as above

2025-01-14 15:51 UTC, AlexBramhill commented on libs/common/src/test-helpers/mock-builders/index.ts
> +export * from './mock-builder.mock.builder';
It's technically a mock builder builder... its odd I know

2025-01-14 15:51 UTC, AlexBramhill commented on libs/common/src/errors/user-partial-login-data-not-defined.error.test.ts
> +    // Act
Great catch -- thanks

2025-01-17 11:54 UTC, ttbarnes commented on libs/common/src/schemas/object-id.ts
> + * This schema does not do any transformation
This comment feels misleading becuase line 18 mentions transformation

Please ignore if it does make sense, I am not familiar with `zod`

2025-01-17 11:58 UTC, ttbarnes reviewed
Nice work

2025-01-17 11:58 UTC, ttbarnes commented on trade-finance-manager-api/src/v1/controllers/sso.controller.ts
> +    try {
Can we add a `console.info` here and `console.error` in the catch handler?

2025-01-17 11:58 UTC, ttbarnes commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-login.test.ts
> +        it('should redirect to login URL', async () => {
```suggestion
        it('should redirect to auth code URL', async () => {
```

2025-01-17 12:23 UTC, MarRobSoftwire commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-login.test.ts
> +          req.session.loginData = { authCodeUrlRequest: 'old-auth-code-url-request' };
is this setting req.session.loginData twice?

2025-01-17 12:23 UTC, MarRobSoftwire commented on trade-finance-manager-api/src/v1/sso/routes.ts
> +ssoOpenRouter.route('/auth-code-url').get(ssoController.getAuthCodeUrl.bind(ssoController));
You've done this in the other router - I think I prefer it
```suggestion
ssoOpenRouter.route('/auth-code-url').get((req, res) => ssoController.getAuthCodeUrl(req,res));
```

2025-01-17 12:23 UTC, MarRobSoftwire commented on trade-finance-manager-ui/server/api.js
> +// TODO DTFS2-6892 - remove this function
Is 6892 the correct ticket - is this removed by a future subtask?

2025-01-17 12:23 UTC, MarRobSoftwire commented on trade-finance-manager-api/package.json
> +    "@azure/msal-node": "^2.16.2",
Should this be uninstalled in tfm-ui? Do ignore If im misunderstanding

2025-01-17 12:24 UTC, AlexBramhill commented on libs/common/src/schemas/object-id.test.ts
> +  withSchemaTests({
This is coming later -- https://github.com/UK-Export-Finance/dtfs2/pull/4034 see this for schema test reworks

2025-01-20 14:30 UTC, ttbarnes commented on libs/common/src/schemas/object-id.ts
> + * This schema does not do any transformation
Bump

2025-01-20 14:30 UTC, ttbarnes commented on trade-finance-manager-api/src/v1/controllers/sso.controller.ts
> +    try {
Bump

2025-01-20 14:30 UTC, ttbarnes commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-login.test.ts
> +        it('should redirect to login URL', async () => {
Bump

2025-01-22 14:51 UTC, AlexBramhill commented on libs/common/src/schemas/object-id.ts
> + * This schema does not do any transformation
That is a really good point. I've clarified how this works

2025-01-22 17:19 UTC, AlexBramhill commented on trade-finance-manager-api/src/v1/sso/routes.ts
> +// eslint-disable-next-line @typescript-eslint/no-misused-promises
I think the actual realistic fix is above -- It'll then catch and pass to express error handler, which is what it was doing anyway

2025-01-22 17:19 UTC, AlexBramhill commented on libs/common/src/schemas/object-id.ts
> +export const OBJECT_ID_OR_OBJECT_ID_STRING = z.union([z.instanceof(ObjectId), OBJECT_ID_STRING]);
No transforms -- see above

2025-01-23 10:19 UTC, ttbarnes commented on trade-finance-manager-api/src/v1/controllers/sso.controller.ts
> +    try {
Thanks @AlexBramhill can we add a `console.info` here immediately after the `try`?

```
console.info('Getting auth code URL');
```

I'm not sure what's available in `entraIdService`, but including an ID might helpful as well

Just thinking of future debugging

2025-01-23 13:44 UTC, AlexBramhill commented on trade-finance-manager-api/src/v1/controllers/sso.controller.ts
> +    try {
I'm not sure the benefit in adding in a log here for this effect -- if it's successful, we don't particularly need worry. If its not successful, we get a full stack trace and error log pointing us to the issue (in fact, logging the error twice as per existing patterns)

Also not sure we should be logging additional login information to console past the errors received from Entra for general security (at this point, we also don't know if the entraIdService has been successful -- if this function throws, then its 99.99% likely its due to the entraIdService throwing, and therefore we have no additional information (the other 0.01% is if res.json throws))

2025-01-23 13:45 UTC, AlexBramhill commented on trade-finance-manager-api/package.json
> +    "@azure/msal-node": "^2.16.2",
Yep -- Was using for types in tests but can remove now

2025-01-23 13:47 UTC, ttbarnes commented on trade-finance-manager-api/src/v1/controllers/sso.controller.ts
> +    try {
Makes sense if it adheres to existing patterns

2025-01-23 13:48 UTC, AlexBramhill commented on trade-finance-manager-api/src/v1/controllers/sso.controller.ts
> +    try {
So fast resolving i thought I accidentally did! :) thanks

2025-01-23 17:16 UTC, rkontogianni commented on libs/common/src/schemas/object-id.ts
> +
@AlexBramhill Is a specific reason you export this and the OBJECT_ID twice ?

2025-01-30 14:00 UTC, rkontogianni commented on trade-finance-manager-ui/server/api.js
>      const response = await axios({
@AlexBramhill why was this added here twice? this function is not correctly close here

2025-01-30 17:25 UTC, rkontogianni approved these changes

2025-02-04 14:53 UTC, rkontogianni approved these changes

2025-02-05 11:55 UTC, merged