feat(DTFS2-7602): portal information banner facilities
UK-Export-Finance/dtfs2 pull request #4030
Opened 2024-12-04 10:50 UTC by rkontogianni

## Introduction :pencil2:
add an information banner on the deal summary page for all deal stages.
add e2e test for AIN and MIN to ensure that banner is populated correctly

## Resolution :heavy_check_mark:
List all changes made to the codebase.

## Miscellaneous :heavy_plus_sign:
List any additional fixes or improvements.

2024-12-04 15:18 UTC, MarRobSoftwire reviewed
Looks good :) just the e2e test changes we discussed

2024-12-04 15:18 UTC, MarRobSoftwire commented on gef-ui/templates/includes/application-preview/facilities.njk
Could you add a component test for this page please? Its fine to just test the new content if it doesnt already exist

2024-12-05 12:31 UTC, abhi-markan requested changes
Few minor changes to address please.

2024-12-05 12:31 UTC, abhi-markan commented on gef-ui/templates/includes/application-preview/facilities.njk
> +{{ mojBanner({
Can the indentation be corrected please.

2024-12-05 12:31 UTC, abhi-markan commented on e2e-tests/gef/cypress/e2e/application/application-preview.spec.js
> +    cy.apiLogin(BANK1_MAKER1)
Can this be a command please so it can be refactored and re-utilised.

2024-12-05 12:31 UTC, abhi-markan commented on e2e-tests/gef/cypress/e2e/application/application-preview.spec.js
> +      const miaDeal = deals.find((deal) => deal.submissionType === DEAL_SUBMISSION_TYPE.MIN);
Should be `minDeal`?

2024-12-05 12:31 UTC, abhi-markan commented on e2e-tests/gef/cypress/e2e/application/application-preview.spec.js
> +  describe('Application preview page with MIA Deal', () => {
Is this for `MIA` or `MIN` please?

2024-12-05 12:32 UTC, abhi-markan commented
Could you also please add a screenshot of the updated page in the PR description as it ease PR review. Thanks.

2024-12-06 11:54 UTC, rkontogianni commented on e2e-tests/gef/cypress/e2e/application/application-preview.spec.js
> +  });
@abhi-markan @MarRobSoftwire why the MIA deal not display ? MIN or MIA has status Acknowledged I thought that was MIA ?

2024-12-09 10:36 UTC, abhi-markan requested changes
Still pending one minor comment please. Thanks

2024-12-09 10:36 UTC, abhi-markan commented on e2e-tests/gef/cypress/e2e/application/application-preview.spec.js
> +    cy.apiLogin(BANK1_MAKER1)
Missed this one.

2024-12-09 11:09 UTC, MarRobSoftwire commented on e2e-tests/gef/cypress/e2e/application/application-preview.spec.js
> +  });
could you add a new line here :)

2024-12-09 11:09 UTC, MarRobSoftwire commented on e2e-tests/gef/cypress/support/commands/createAndConfigureApplicationStatus.js
> +      cy.wrap(response.body);
I'm not familiar with `wrap` - is this doing anything?

2024-12-09 14:32 UTC, ttbarnes requested changes
Nice work, few minor comments

2024-12-09 14:32 UTC, ttbarnes commented on e2e-tests/gef/cypress/e2e/application/application-preview.spec.js
> +    // ensures that banner is not displayed
Can we remove this comment please, the test itself does the same thing 😄 

Same with other tests

2024-12-09 14:32 UTC, ttbarnes commented on e2e-tests/gef/cypress/support/commands/createAndConfigureApplicationStatus.js
> +export const createAndConfigureApplicationStatus = (mockDeal, mockCashFacility, mockContingentFacility, dealStatus) => {
Can we add some documentation please

2024-12-09 14:32 UTC, ttbarnes commented on e2e-tests/gef/cypress/support/commands/createAndConfigureApplicationStatus.js
> +          if (mockContingentFacility) {
Can we add a new line before this please for readability

2024-12-09 14:32 UTC, ttbarnes commented on e2e-tests/gef/cypress/support/commands/createAndConfigureApplicationStatus.js
> +export const createAndConfigureApplicationStatus = (mockDeal, mockCashFacility, mockContingentFacility, dealStatus) => {
What do you think about `createApplicationAndSetStatus`?

2024-12-09 15:43 UTC, abhi-markan approved these changes
LGTM 👍🏼

2024-12-09 15:56 UTC, ttbarnes approved these changes
Nice work

2024-12-09 15:58 UTC, merged