feat(dtfs2-6892): update tfm to save token
UK-Export-Finance/dtfs2 pull request #4052
Opened 2024-12-09 18:31 UTC by AlexBramhill

## Introduction :pencil2:
After performing checks and issuing a token in tfm api, we need to save the token in tfm ui.

## Resolution :heavy_check_mark:
This PR adds tfm ui changes to handle saving the token

## Miscellaneous :heavy_plus_sign:
List any additional fixes or improvements.

2024-12-11 11:16 UTC, ttbarnes commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +  async handleSsoRedirectForm(req: HandleSsoRedirectFormUiRequest, res: Response, next: NextFunction) {
Unit test?

2024-12-11 11:17 UTC, ttbarnes commented on trade-finance-manager-ui/server/services/login.service.ts
> +    // TODO as part of this ticket: uncomment the session parameter
TODO?

2024-12-11 11:17 UTC, ttbarnes commented on trade-finance-manager-ui/server/services/login.service.ts
> +    // TODO: This can be moved into a separate session service
Do we need to leave this here / new ticket?

2025-01-03 11:09 UTC, abhi-markan commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> +  // eslint-disable-next-line @typescript-eslint/no-misused-promises
I haven't changed this but will following resolve the eslint error on promise being returned.

```js
  authSsoRouter.post('/auth/sso-redirect/form', (req, res, next) => {
    loginController.handleSsoRedirectForm(req, res).catch(next);
  });
```

2025-01-03 11:17 UTC, abhi-markan requested changes
@AlexBramhill I have pushed my changes and left a comment can you please review this PR. Thanks

2025-01-15 15:07 UTC, AlexBramhill commented on trade-finance-manager-ui/server/api.js
> + */
These need to be kept in for intellisence

2025-01-15 15:32 UTC, AlexBramhill commented on trade-finance-manager-ui/server/api.js
> +    console.error('An exception has occurred while handling TFM SSO %o', error?.response?.data);
Reverted this change as we should be login additional description for our troubleshooting

2025-01-15 15:35 UTC, AlexBramhill commented on trade-finance-manager-ui/server/api.js
> +    return HANDLE_SSO_REDIRECT_FORM_RESPONSE_SCHEMA.parse(response.data);
Reverted as we should only ever return the object stated in the JSdoc, or throw an error

2025-01-15 15:49 UTC, AlexBramhill commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
>        }
Reverting the change from `/deals` to `/home` as home provides important rooting -- including routing non logged in users to be able to log in

2025-01-15 15:50 UTC, AlexBramhill commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +   */
Removing throws comment as this function does not throw

2025-01-15 15:55 UTC, AlexBramhill commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
>          // User is already logged in.
I'm not sure the reason for the optional change here -- Reverting from `req?.session?.user` as far as im aware there will always be a request, and there will always be a user session (even if not logged in)?

2025-01-15 16:39 UTC, AlexBramhill commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +      return res.render('_partials/problem-with-service.njk');
I'm reverting this from `%O` to `%o` as we probably want the developer friendly logs -- I'm not sure we ever need to see the prototypes etc of the error?

2025-01-15 16:40 UTC, AlexBramhill commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +   * @returns {Promise<void>} - A promise that resolves when the operation is complete.
Removing the throw as the function not throwing an invalid payload error

2025-01-15 16:45 UTC, AlexBramhill commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> + */
I'm removing type from this -- as this is a typescript file and we shouldn't be overriding types with jsdocs in ts files

2025-01-15 16:48 UTC, AlexBramhill commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +   */
Removing as we should never type JSDocs as they take precedent over typescript -- This has caused bugs such as if we have a ts file that returns a promise, but we say in jsdocs it returns an object, we won't have to await it (in addition to mucking up the intellisense)

2025-01-21 17:16 UTC, abhi-markan requested changes
Few comments to address please.

2025-01-21 17:16 UTC, abhi-markan commented on trade-finance-manager-ui/server/routes/login/configs/login-sso.ts
> +    loginController.getLogin(req, res).catch(next);
Does this not require any sort of middleware validation?

2025-01-21 17:16 UTC, abhi-markan commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> + */
We need to keep DocString consistent as we use JSDocs across TS.

2025-01-21 17:16 UTC, abhi-markan commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> +  // Todo: update this to check the right token
Ticket number please.

2025-01-21 17:16 UTC, abhi-markan commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +      return res.redirect(successRedirect ?? '/');
```suggestion
      const url = successRedirect ?? '/';
      return res.redirect(url);
```

2025-01-21 17:16 UTC, abhi-markan commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +      console.error('Unable to log in user: %o', error);
```suggestion
      console.error('Unable to log in user %o', error);
```

2025-01-21 17:16 UTC, abhi-markan commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +   */
DocString with type please.

2025-01-21 17:16 UTC, abhi-markan commented on trade-finance-manager-ui/server/api.js
> + */
The above does not output correct type, rather outputs the location.

2025-01-22 10:09 UTC, vamshidharukef commented on libs/common/src/test-helpers/schemas/schema-tests/with-tfm-session-user-schema.tests.ts
> +  };
can `CONSTANTS` be used instead of hard coding similar to `teams`

2025-01-22 12:42 UTC, vamshidharukef commented on trade-finance-manager-api/src/v1/__mocks__/builders/extra-id.service.mock.builder.ts
> +import { aGetAuthCodeUrlResponse, anEntraIdUser, BaseMockBuilder } from '@ukef/dtfs2-common';
add docString 
/**
   * Constructs a new instance of the EntraIdServiceMockBuilder.
   *
   * The default instance returned by the builder has the following properties:
   * - `getAuthCodeUrl` returns a resolved promise with a valid `GetAuthCodeUrlResponse` object.
   * - `handleRedirect` returns a resolved promise with an object that contains the following properties:
   *   - `entraIdUser`: a valid `EntraIdUser` object.
   *   - `successRedirect`: a string set to `a-success-redirect`.
   */

2025-01-22 12:59 UTC, vamshidharukef commented on trade-finance-manager-api/src/v1/__mocks__/builders/user.service.mock.builder.ts
can this be changed to SaveUserLoginInformationParams

2025-01-22 13:02 UTC, vamshidharukef commented on trade-finance-manager-api/src/v1/__mocks__/builders/user.service.mock.builder.ts
> +    const userService = new UserService();
add docString above export class 
/**
 * Mock builder for UserService.
 */

2025-01-22 13:03 UTC, vamshidharukef commented on trade-finance-manager-api/src/v1/__mocks__/builders/user.service.mock.builder.ts
> +         * as it is an existing pattern that we never mock synchronous methods.
add 
* @param {EntraIdUser} entraIdUser - The EntraId user object.
* @returns {UpsertTfmUserRequest} - The transformed user request.

2025-01-22 13:05 UTC, vamshidharukef commented on trade-finance-manager-api/src/v1/__mocks__/builders/user.service.mock.builder.ts
> +        },
please add 
/**
         * Mock implementation for upserting a TFM user from EntraId user.
         * 
         * @param {UpsertTfmUserFromEntraIdUserParams} params - The parameters for upserting the user.
         * @returns {Promise<UpsertTfmUserFromEntraIdUserResponse>} - A promise that resolves to the upserted user response.
         */

2025-01-22 14:27 UTC, vamshidharukef commented on trade-finance-manager-api/src/v1/controllers/sso.controller.get-auth-code-url.test.ts
change to 'should return a 200 status'

2025-01-24 17:17 UTC, AlexBramhill reviewed
Should have addressed all comments

2025-01-24 17:17 UTC, AlexBramhill commented on trade-finance-manager-ui/server/api.js
> + */
Works in my ide when hovering over `HandleSsoRedirectFormResponse`

2025-01-24 17:17 UTC, AlexBramhill commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +      console.error('Unable to log in user: %o', error);
Updated

2025-01-24 17:17 UTC, AlexBramhill commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +      return res.redirect(successRedirect ?? '/');
updated

2025-01-24 17:17 UTC, AlexBramhill commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> + */
Agreed, but we should not use types in JSDocs in a typescript file as these override the inferred types in a ts file. 

This was the reason we had some async files not being awaited without any errors, causing several bugs. The docs listed `returns {something}`, whereas it was really `returns {Promise<something>}`. Things like this are free in TS through type inference and help us avoid bugs, and the inclusion of typed jsdocs in typescript only create maintenance and potential bug areas (I really dislike how it allows you to override TS types without TS warning it's not okay).

2025-01-24 17:17 UTC, AlexBramhill commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> +  // Todo: update this to check the right token
Opps -- This is for this ticket and I'll leave this comment open until I can remove this comment

2025-01-24 17:17 UTC, AlexBramhill commented on trade-finance-manager-ui/server/routes/login/configs/login-sso.ts
> +    loginController.getLogin(req, res).catch(next);
It has some rate limiting (in a future review) and generally applied `generateApp` middleware, what would you be expecting?

2025-01-24 17:17 UTC, AlexBramhill commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> +  // eslint-disable-next-line @typescript-eslint/no-misused-promises
Fwiw, we'd discussed this as I was hoping to put in a generic error handler in express to avoid the default one in this case -- but happy to add this in and let it hit the generic for now.

2025-01-24 17:17 UTC, AlexBramhill commented on trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
> +  async handleSsoRedirectForm(req: HandleSsoRedirectFormUiRequest, res: Response, next: NextFunction) {
added

2025-01-27 11:19 UTC, vamshidharukef commented on trade-finance-manager-api/src/v1/controllers/sso.controller.get-auth-code-url.test.ts
is it documented.

2025-01-27 11:46 UTC, vamshidharukef commented on libs/common/src/test-helpers/schemas/schema-tests/with-tfm-session-user-schema.tests.ts
> +  };
good explanation @AlexBramhill :)

2025-02-10 17:51 UTC, rkontogianni submitted a review, later dismissed

2025-02-13 09:42 UTC, abhi-markan requested changes

2025-02-13 09:42 UTC, abhi-markan commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> +  // Todo: update this to check the right token
Can this be removed?

2025-02-13 16:36 UTC, AlexBramhill commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> +  // Todo: update this to check the right token
Yep -- was removed in a later pr but remvoed now

2025-02-14 10:03 UTC, abhi-markan requested changes

2025-02-14 10:03 UTC, abhi-markan commented on libs/common/src/test-helpers/schemas/schema-tests/with-tfm-session-user-schema.tests.ts
> +    email: 'test-user@test.com',
```suggestion
    email: 'test-user@ukexportfinance.gov.uk',
```

2025-02-14 10:03 UTC, abhi-markan commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> +  authSsoRouter.post('/auth/sso-redirect/form', (req, res, next) => {
Can `req`, `res` have custom types to keep it inline please.

2025-02-14 10:10 UTC, AlexBramhill commented on trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
> +  authSsoRouter.post('/auth/sso-redirect/form', (req, res, next) => {
These methods are going to be deleted in future PRs -- To avoid wasting time fixing up tests/merge conflicts, I've got a note to check this after they're all merged in if that's okay

2025-02-14 10:37 UTC, AlexBramhill commented on trade-finance-manager-ui/server/services/user-session.service.ts
> +import { AuthorizationUrlRequest } from '@azure/msal-node';
There's not a nice way around having this as a dependency, which is slightly a shame.

2025-02-14 12:12 UTC, merged