chore(DTFS2-7708): updated dependabot.yml
UK-Export-Finance/dtfs2 pull request #4077
Opened 2024-12-13 10:24 UTC by Zainzzkk

## Introduction :pencil2:
This PR updates the dependabot.yml file

## Resolution :heavy_check_mark:
* Grouped PRs for each directory in dependabot.yml

2024-12-13 10:31 UTC, abhi-markan requested changes

2024-12-13 10:31 UTC, abhi-markan commented on .github/dependabot.yml
> +    groups:
Can these grouped same as DockerFile?

2024-12-13 11:39 UTC, Zainzzkk commented on .github/dependabot.yml
> +    groups:
You want them all in 1 PR?

2024-12-19 17:31 UTC, abhi-markan approved these changes

2024-12-19 18:31 UTC, merged