feat(FN-3667): pending corrections list on portal
UK-Export-Finance/dtfs2 pull request #4086
Opened 2024-12-17 17:41 UTC by RLavender98

## Introduction :pencil2:
When a PDC user has requested a correction we need to give the bank users a way to view the request and action it. This will happen by when they go to the report upload page if there are any correction requests that need a response displaying them in a table instead of displaying the report upload. 

## Resolution :heavy_check_mark:
- Add a new central-api endpoint to fetch all pending corrections from the oldest report with pending corrections for a bank.
- Update the get upload controller to check if the feature flag is enabled and if so check for pending corrections and if there are any render the pending corrections template instead of the report upload template.
- New pending corrections template for the new view of the page.

## Miscellaneous :heavy_plus_sign:
- Rewrite some existing controllers and tests written in javascript in typescript
- e2e-test set up for record correction tests in portal

2025-01-03 11:32 UTC, RLavender98 commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/helpers.ts
> + * - The next report period in the bank's schedule if there are no not received reports
Have gone with explicitly using the report status

2025-01-03 11:35 UTC, RLavender98 commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/index.ts
> +      // If there aren't any reports with pending corrections then we return null.
I think what I was trying to explain was that if there is no oldest report with pending corrections, then there are no reports at all with pending corrections. I have reworded a little, let me know if you still think it is unnecessary.

2025-01-03 16:53 UTC, sw-mattw commented on portal/component-tests/utilisation-report-service/record-corrections/pending-corrections.component-test.js
> +      wrapper.expectElement('th:contains("Facility ID")').toExist();
MATT: NOT SURE ON THIS

2025-01-03 16:53 UTC, sw-mattw commented on portal/templates/utilisation-report-service/record-corrections/pending-corrections.njk
> +{% block pageTitle %}Report GEF utilisation and fees - Record correction{% endblock %}
Thanks

2025-01-03 16:59 UTC, sw-mattw requested changes

2025-01-03 16:59 UTC, sw-mattw commented on portal/component-tests/utilisation-report-service/record-corrections/pending-corrections.component-test.js
> +      wrapper.expectElement('th:contains("Facility ID")').toExist();
Second and third should be `Exporter` and `Error summary`

2025-01-06 09:24 UTC, sw-mattw submitted a review, later dismissed

2025-01-06 10:24 UTC, Zainzzkk commented on dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-utilisation-report-pending-corrections.api-test.ts
> +    const completedCorrection = FeeRecordCorrectionEntityMockBuilder.forFeeRecord(feeRecord)
new lines please between these

2025-01-06 10:24 UTC, Zainzzkk commented on dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-utilisation-report-pending-corrections.api-test.ts
> +        reportPeriod: oldestReportWithPendingCorrections.reportPeriod,
can this be an expected object please

2025-01-06 10:28 UTC, Zainzzkk commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/helpers.test.ts
> +    it(`should return an array of all of the pending corrections of the fee records`, () => {
can more be added to this it (like the ones above) for why an array is being returned

2025-01-06 10:29 UTC, Zainzzkk commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/helpers.test.ts
this test file is very long and hard to follow.  Can it be split into one for each helper?

2025-01-06 10:29 UTC, Zainzzkk commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/helpers.ts
> +  return dueReports[0].reportPeriod;
new lines please in this file

2025-01-06 10:30 UTC, Zainzzkk commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/helpers.ts
> +  if (report.uploadedByUserId === null || report.dateUploaded === null) {
could this be `!report.uploadedByUserId  || !report.dateUploaded`

2025-01-06 10:31 UTC, Zainzzkk commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/index.test.ts
> +    describe('when the bank is not opted into utilisation reporting via DTFS', () => {
should this be has not?

2025-01-06 10:33 UTC, Zainzzkk commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/index.ts
> +      throw new NotFoundError(`Bank with id '${bankId}' is not opted into utilisation reporting via DTFS`);
has not?

2025-01-06 10:35 UTC, Zainzzkk commented on e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-disabled/pending-corrections.spec.js
> +context('Pending corrections - Fee record correction feature flag enabled', () => {
this is in feature flag enabled folder

2025-01-06 10:36 UTC, Zainzzkk commented on e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-disabled/pending-corrections.spec.js
> +      });
can this be in the before so the it statement is much shorter

2025-01-06 10:37 UTC, Zainzzkk commented on e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/pending-corrections.spec.js
> +          const feeRecord = FeeRecordEntityMockBuilder.forReport(report)
new lines so easier to read please

2025-01-06 10:40 UTC, Zainzzkk commented on e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/pending-corrections.spec.js
> +          cy.task('getUserFromDbByEmail', BANK1_PAYMENT_REPORT_OFFICER1.email).then((user) => {
could this be in a before and the login in a beforeEach so we are not doing this call for every it statement?

2025-01-06 10:42 UTC, Zainzzkk commented on portal-api/src/v1/api-response-types/utilisation-report-pending-corrections-response-body.ts
> +};
libs/common? also being used in `dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/index.ts`

2025-01-06 10:43 UTC, Zainzzkk commented on portal-api/src/v1/api-response-types/utilisation-report-pending-corrections-response-body.ts
> +export type UtilisationReportPendingCorrectionsResponseBody =
could this also be in libs/common?

2025-01-06 10:44 UTC, Zainzzkk commented on portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/pending-corrections.ts
> +    return res.status(200).send(pendingCorrections);
HttpStatus.ok instead?

2025-01-06 10:46 UTC, Zainzzkk commented on portal/component-tests/utilisation-report-service/record-corrections/pending-corrections.component-test.js
> +        `The following errors in the ${viewModel.formattedReportPeriod} report uploaded by ${viewModel.uploadedByFullName} on ${viewModel.formattedDateUploaded} have been identified by UKEF:`,
could this be a const since it's a long string being constructed?

2025-01-06 10:53 UTC, Zainzzkk commented on portal/server/controllers/utilisation-report-service/utilisation-report-upload/pending-corrections-helper.test.ts
> +      expect(result).toBe(true);
toEqual?

2025-01-06 10:56 UTC, Zainzzkk commented on portal/test-helpers/test-data/portal-session-bank.ts
this already exists in libs/common/src/test-helpers/bank.ts

2025-01-06 10:56 UTC, Zainzzkk commented on portal/test-helpers/test-data/report-period.ts
could this also go in libs/common.  could be reused

2025-01-06 10:57 UTC, Zainzzkk commented on portal/test-helpers/test-data/utilisation-reporting-schedule.ts
this as well

2025-01-06 10:57 UTC, Zainzzkk commented on e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/record-corrections/pendingCorrections.js
> +    facilityId: () => cy.get(`[data-cy="pending-corrections-table"] tr:nth-child(${index}) [data-cy="pending-corrections-row--facility-id"]`),
could each row not use a correctionId so we don't need to find by row index?

2025-01-06 10:57 UTC, RLavender98 commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/index.test.ts
> +    describe('when the bank is not opted into utilisation reporting via DTFS', () => {
I guess semantically the bank doesn't opt themselves in which I would expect to be the case with the wording 'the bank has'

2025-01-06 13:40 UTC, RLavender98 commented on e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/pending-corrections.spec.js
> +          cy.task('getUserFromDbByEmail', BANK1_PAYMENT_REPORT_OFFICER1.email).then((user) => {
I don't think so because I can't see a way to clean up that doesn't use an afterEach deleting everything without deleting specific entities which is not something we should do because that is harder to maintain and less reliable

2025-01-06 13:45 UTC, RLavender98 commented on portal-api/src/v1/api-response-types/utilisation-report-pending-corrections-response-body.ts
> +export type UtilisationReportPendingCorrectionsResponseBody =
We haven't been doing this for types which differ in central api because the response body is quite tied to the service and we don't want people getting confused about which services they belong in, e.g. this type is different in central-api because in central-api the date uploaded is a `Date` but in the apis consuming it it will have been stringified into an `IsoDateTimeStamp` so the types are different in different services.

2025-01-06 13:58 UTC, RLavender98 commented on portal/test-helpers/test-data/report-period.ts
I'm not sure we should be putting so many test only helpers into libs common because they will get packaged up with the actual main code when the project is built and increase the size of the packaged library no? Or is that not a concern?

2025-01-06 14:00 UTC, RLavender98 commented on e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/record-corrections/pendingCorrections.js
> +    facilityId: () => cy.get(`[data-cy="pending-corrections-table"] tr:nth-child(${index}) [data-cy="pending-corrections-row--facility-id"]`),
I guess we could, but I thought this was pretty nice and will be useful when we are doing e2e tests for the full complete journey where we won't know what the id is.

2025-01-06 14:23 UTC, Zainzzkk commented on portal/test-helpers/test-data/report-period.ts
I am thinking that this may be reused in another microservice such as central-api? would be better than replication.  Can keep it here for now

2025-01-06 14:37 UTC, Zainzzkk commented on e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/record-corrections/pendingCorrections.js
> +    facilityId: () => cy.get(`[data-cy="pending-corrections-table"] tr:nth-child(${index}) [data-cy="pending-corrections-row--facility-id"]`),
lets leave it for now.  I have something in my PR to find the record correction id so we can refactor later once my PR is in

2025-01-06 14:45 UTC, Zainzzkk submitted a review, later dismissed

2025-01-06 17:01 UTC, Zainzzkk approved these changes

2025-01-06 17:28 UTC, Zainzzkk commented on portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.ts
> +  (req.session as LoggedInUserSession).utilisationReport = {
from sonarCloud - This assertion is unnecessary since it does not change the type of the expression. (as LoggedInUserSession not needed)

2025-01-06 17:30 UTC, Zainzzkk commented on portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.ts
> +      (req.session as LoggedInUserSession).utilisationReport = {
same as above

2025-01-06 17:49 UTC, RLavender98 commented on portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.ts
> +  (req.session as LoggedInUserSession).utilisationReport = {
If I remove it I get the following:
<img width="954" alt="Screenshot 2025-01-06 at 17 47 35" src="https://github.com/user-attachments/assets/6187fa52-463e-4f41-b889-29740ab4fafb" />

2025-01-06 17:50 UTC, Zainzzkk commented on portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.ts
> +  (req.session as LoggedInUserSession).utilisationReport = {
can ignore this one then

2025-01-06 17:50 UTC, RLavender98 commented on portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.ts
> +      (req.session as LoggedInUserSession).utilisationReport = {
Same as above

2025-01-06 17:59 UTC, Zainzzkk approved these changes

2025-01-07 08:37 UTC, sw-mattw commented on dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/helpers/index.test.ts
> +          jest.mocked(getUserById).mockRejectedValue(mockError);
[Failing tests](https://github.com/UK-Export-Finance/dtfs2/actions/runs/12637660031/job/35212362990?pr=4086) - Missing `jest.mock` for users-repo at the top of the file maybe?

2025-01-07 11:08 UTC, merged