Changed the facilityValue to facility to keep BSS and GEF consistent
UK-Export-Finance/dtfs2 pull request #541
Opened 2021-12-16 13:13 UTC by IgnatG

2021-12-16 18:59 UTC, ttbarnes commented on dtfs-central-api/src/v1/swagger-definitions/portal/facility-ewcs.js
> + *       premiumFrequency:
whoa, good spot

2021-12-16 19:03 UTC, ttbarnes reviewed
*Great* work, bonus points for fixing the typos(!) Can approve when the tests are passing 👍

2021-12-17 08:44 UTC, abhi-markan requested changes
Can you please resolve the conflicts, but great work!

2021-12-20 11:32 UTC, ttbarnes approved these changes
LGTM, great work!

2021-12-20 11:45 UTC, abhi-markan approved these changes

2021-12-20 12:03 UTC, merged