DTFS2-2071 BSS - table overflow
UK-Export-Finance/dtfs2 pull request #671
Opened 2022-02-07 17:30 UTC by Zainzzkk

# Changes made: 

* For BSS tables, added a div with overflow class
* Added CSS style for overflow-x

2022-02-07 17:33 UTC, IgnatG submitted a review, later dismissed

2022-02-07 17:33 UTC, ttbarnes submitted a review, later dismissed

2022-02-07 17:40 UTC, abhi-markan requested changes

2022-02-07 17:40 UTC, abhi-markan commented on portal/templates/contract/components/contract-overview-table.njk
> +            {{ deal.bankInternalRefName | dashIfEmpty }}
Please add `| safe` filter along all displayed items.

2022-02-07 17:40 UTC, abhi-markan commented on portal/templates/contract/components/loan-transactions-table.njk
> +                  {{ loan.ukefFacilityId }}
`safe |` filter for all display cells.

2022-02-08 09:39 UTC, Zainzzkk commented on portal/templates/contract/components/loan-transactions-table.njk
> +                  {{ loan.ukefFacilityId }}
done

2022-02-08 09:39 UTC, Zainzzkk commented on portal/templates/contract/components/contract-overview-table.njk
> +            {{ deal.bankInternalRefName | dashIfEmpty }}
done

2022-02-08 09:43 UTC, abhi-markan requested changes

2022-02-08 09:43 UTC, abhi-markan commented on portal/templates/contract/components/contract-overview-table.njk
> +            {{ deal.bankInternalRefName | dashIfEmpty }}
Missing filter here.

2022-02-08 09:43 UTC, abhi-markan commented on portal/templates/contract/components/contract-overview-table.njk
> +            {{ details.ukefDealId | dashIfEmpty}}
Missing filters on all the cells here.

2022-02-08 09:49 UTC, Zainzzkk commented on portal/templates/contract/components/contract-overview-table.njk
> +            {{ deal.bankInternalRefName | dashIfEmpty }}
done

2022-02-08 09:49 UTC, Zainzzkk commented on portal/templates/contract/components/contract-overview-table.njk
> +            {{ details.ukefDealId | dashIfEmpty}}
done

2022-02-08 10:28 UTC, abhi-markan approved these changes

2022-02-08 10:28 UTC, merged