DTFS2 :  GitHub Runners
UK-Export-Finance/dtfs2 pull request #726
Opened 2022-02-22 18:46 UTC by abhi-markan

`self-hosted` Git hub runners

2022-02-22 18:49 UTC, IgnatG submitted a review, later dismissed

2022-02-22 21:08 UTC, Zainzzkk submitted a review, later dismissed
LGTM

2022-02-23 08:00 UTC, IgnatG requested changes
shall we make a few more changes to it to include new app service plans? - this since it's going to rebuild the infrastructure anyway
(we can discuss it on slack)

2022-02-23 11:54 UTC, abhi-markan commented
> shall we make a few more changes to it to include new app service plans? - this since it's going to rebuild the infrastructure anyway (we can discuss it on slack)

Sounds good

2022-02-25 10:48 UTC, closed without merging